<a href="https://colab.research.google.com/github/manishgurungxon/MachineLearningPy/blob/main/MachineLearningwithpython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Preprocessing
The phas where the datasets are cleaned, transformed and reduced before feeding it to the Machine. 
Concepts in Machine Learning:
1. Import Python Libraries
a. Pandas
b. Numpy
c. Matplotlib + seaborn
d. Scikit-learn
e. Tensorflow
f. Theano
g. Scipy
2. Import Dataset
a. read_csv
b. read_json
c. url
3. Divide data into independent and Dependent
*   X ( Independent )
*   Y ( Dependent )
4. Missing Data
*   Mean
*   Median
*   Constant
*   Most Frequent
5. Categorical Data
*   OneHotEncoder
*   LabelEncoder
6. Splitting Data into Train and Test model
a. Train(75-90%)
b. Test(10-25%)
7. Feature Scaling
a. StandardScaler(Normalization)







In [1]:
#import libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as pyplot


In [2]:
df = pd.read_csv('Data.csv')

In [3]:
df.head()

Country  Confirmed_Cases  Suspected_Cases  Hospitalized  \
0        England           3412.0              0.0           5.0   
1       Portugal            908.0              0.0           0.0   
2          Spain           7083.0              0.0          13.0   
3  United States          24403.0              0.0           4.0   
4         Canada           1388.0             12.0           1.0   

   Travel_History_Yes  Travel_History_No  
0                 2.0                7.0  
1                 0.0               34.0  
2                 2.0                0.0  
3                41.0               11.0  
4                 5.0                0.0

In [4]:
# Divide the data into Independent and Dependent

X = df.iloc[:,0:-2].values
Y = df.iloc[:,-1:].values


In [5]:
print(X)

[['England' 3412.0 0.0 5.0]
 ['Portugal' 908.0 0.0 0.0]
 ['Spain' 7083.0 0.0 13.0]
 ['United States' 24403.0 0.0 4.0]
 ['Canada' 1388.0 12.0 1.0]
 ['Sweden' 186.0 0.0 0.0]
 ['Italy' 837.0 0.0 18.0]
 ['France' 3934.0 0.0 1.0]
 ['Belgium' 757.0 0.0 2.0]
 ['Australia' 132.0 0.0 2.0]
 ['Germany' 3590.0 0.0 18.0]
 ['Netherlands' 1221.0 0.0 0.0]
 ['Israel' 250.0 0.0 3.0]
 ['Switzerland' 503.0 0.0 0.0]
 ['Greece' 72.0 0.0 2.0]
 ['Austria' 304.0 0.0 2.0]
 ['Argentina' 326.0 0.0 0.0]
 ['Denmark' 183.0 0.0 0.0]
 ['Morocco' 3.0 0.0 0.0]
 ['Slovenia' 46.0 0.0 0.0]
 ['Scotland' 93.0 0.0 1.0]
 ['Czech Republic' 66.0 0.0 1.0]
 ['United Arab Emirates' 16.0 0.0 0.0]
 ['Finland' 33.0 0.0 0.0]
 ['Wales' 46.0 0.0 0.0]
 ['Northern Ireland' 34.0 0.0 0.0]
 ['Sudan' 6.0 1.0 0.0]
 ['Bolivia' 155.0 0.0 5.0]
 ['Iran' 1.0 3.0 0.0]
 ['Ecuador' 93.0 1.0 2.0]
 ['Malta' 33.0 0.0 0.0]
 ['Ireland' 178.0 0.0 0.0]
 ['Mexico' 1367.0 0.0 0.0]
 ['Pakistan' 0.0 1.0 1.0]
 ['French Guiana' 0.0 0.0 0.0]
 ['Thailand' 8.0 0.0 4.0

In [6]:
print(Y)

[[ 7.]
 [34.]
 [ 0.]
 [11.]
 [ 0.]
 [ 0.]
 [ 4.]
 [ 1.]
 [ 0.]
 [ 0.]
 [16.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 4.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 4.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [7]:
#Mean
(df.Confirmed_Cases.sum())/129

505.5426356589147

In [8]:
(df.Travel_History_Yes.sum())/129

2.124031007751938

In [9]:
(df.Travel_History_No.sum())/129

0.7054263565891473

In [10]:
# Missing Data
#from sklearn.impute import SimpleImputer
#imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
#Link for sklearn.impute.SimpleImputer 
#https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html
#imputer.fit(X[:,1:4])
#X[:,1:4] = imputer.transform(X[:,1:4])
#X
#from sklearn.impute import SimpleImputer
#imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
#imputer.fit(X[10:,1:4])
#X[:,1:4]= imputer.transform(X[:,1:4])
#X

In [11]:
#Categorical Data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
Y = ct.fit_transform(Y).toarray()

X = ct.fit_transform(X).toarray()



In [12]:
#
#le = LabelEncoder()
#Y = le.fit_transform(Y)
#Y

In [13]:
# Splitting to train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size=0.8, random_state=0)


In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 4:] = sc.fit_transform(X_train[:, 4:])
X_test[:, 4:] = sc.transform(X_test[:, 4:])

In [15]:
X_train, X_test, y_train, y_test

(array([[ 0.        ,  0.        ,  0.        , ..., -0.18324993,
         -0.11173112, -0.05475055],
        [ 0.        ,  1.        ,  0.        , ..., -0.05443923,
         -0.11173112, -0.48854341],
        [ 0.        ,  0.        ,  0.        , ..., -0.18126211,
         -0.11173112, -0.48854341],
        ...,
        [ 0.        ,  0.        ,  0.        , ..., -0.16217904,
         -0.11173112, -0.48854341],
        [ 0.        ,  0.        ,  0.        , ..., -0.18364749,
         -0.11173112, -0.05475055],
        [ 0.        ,  0.        ,  0.        , ..., -0.18205724,
         -0.11173112, -0.48854341]]),
 array([[ 0.        ,  0.        ,  0.        , ..., -0.14826431,
         -0.11173112, -0.48854341],
        [ 0.        ,  0.        ,  0.        , ..., -0.16575712,
         -0.11173112, -0.48854341],
        [ 0.        ,  0.        ,  0.        , ..., -0.18285236,
         -0.11173112, -0.48854341],
        ...,
        [ 0.        ,  0.        ,  0.        , ..., -